#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__))
require 'lib/ezgit/version'
system("gem uninstall -x ezgit")
system("gem build ezgit.gemspec")
system("gem install --no-rdoc --no-ri ./ezgit-#{Ezgit::VERSION}.gem")